name: spatial-extractions
channels:
  - conda-forge
dependencies:
  - python=3.10
  - flask
  - flask-cors
  - flask-wtf
  - flask-migrate
  - flask-sqlalchemy
  - geopandas
  - shapely
  - folium
  - gunicorn
  - werkzeug
  - requests
  - pip
  - pip:
      - wtforms

