name: spatial-extractions
channels:
  - conda-forge
  - esri
dependencies:
  - python=3.11
  - flask
  - flask-cors
  - flask-wtf
  - flask-migrate
  - flask-sqlalchemy
  - geopandas
  - pandas
  - numpy
  - folium
  - gunicorn
  - werkzeug
  - requests
  - rasterio
  - rasterstats
  - retrying
  - openai
  - arcgis=2.3.1
  - pip
  - pip:
      - wtforms


