name: spatial-extractions
channels:
  - conda-forge
  - esri
dependencies:
  - python=3.10
  - flask
  - flask-cors
  - flask-wtf
  - flask-migrate
  - flask-sqlalchemy
  - geopandas
  - pandas
  - numpy
  - shapely
  - folium
  - gunicorn
  - werkzeug
  - requests
  - arcgis
  - rasterio
  - rasterstats
  - retrying
  - pip
  - pip:
      - wtforms

